import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { LessonForm } from '../components/forms/LessonForm'
import { useCurriculum, useCurriculumAction } from '../features/curriculum/hooks/useCurriculum'
import { sectionFormSchema, type LessonFormValues } from '../features/curriculum/schemas/curriculumSchemas'
import { curriculumApi } from '../features/curriculum/services/curriculumApi'
import type { CurriculumLesson } from '../features/curriculum/types/curriculum'
import { ConfirmationDialog } from '../components/common/ConfirmationDialog'
import { useToast } from '../features/toasts/useToast'

export function CurriculumEditorPage() {
  const { id } = useParams()
  const courseId = id ?? ''
  const query = useCurriculum(id)
  const action = useCurriculumAction(courseId)
  const [newSectionTitle, setNewSectionTitle] = useState('')
  const [editingSection, setEditingSection] = useState<string | null>(null)
  const [sectionTitle, setSectionTitle] = useState('')
  const [addingLessonTo, setAddingLessonTo] = useState<string | null>(null)
  const [editingLesson, setEditingLesson] = useState<CurriculumLesson | null>(null)
  const [confirmation, setConfirmation] = useState<{ title: string; description: string; action: (token: string) => Promise<unknown> } | null>(null)
  const { showToast } = useToast()

  const run = async (request: Parameters<typeof action.mutateAsync>[0]) => { await action.mutateAsync(request) }
  const addSection = async (event: FormEvent) => { event.preventDefault(); const parsed = sectionFormSchema.safeParse({ title: newSectionTitle }); if (!parsed.success) return; await run((token) => curriculumApi.addSection(courseId, parsed.data.title, token)); setNewSectionTitle('') }
  const saveSection = async (sectionId: string) => { const parsed = sectionFormSchema.safeParse({ title: sectionTitle }); if (!parsed.success) return; await run((token) => curriculumApi.editSection(courseId, sectionId, parsed.data.title, token)); setEditingSection(null) }
  const moveSection = async (index: number, change: -1 | 1) => { const ids = query.data!.sections.map((section) => section.id); [ids[index], ids[index + change]] = [ids[index + change]!, ids[index]!]; await run((token) => curriculumApi.reorderSections(courseId, ids, token)) }
  const moveLesson = async (sectionId: string, index: number, change: -1 | 1) => { const section = query.data!.sections.find((item) => item.id === sectionId)!; const ids = section.lessons.map((lesson) => lesson.id); [ids[index], ids[index + change]] = [ids[index + change]!, ids[index]!]; await run((token) => curriculumApi.reorderLessons(courseId, sectionId, ids, token)) }

  if (query.isPending) return <div className="mx-auto w-full max-w-5xl px-4 py-16 text-slate-600">Loading curriculum…</div>
  if (query.isError || !query.data) return <div className="mx-auto w-full max-w-3xl px-4 py-16"><h1 className="text-3xl font-bold">Curriculum unavailable</h1><p className="mt-3 text-slate-600">This course does not exist or does not belong to you.</p></div>
  const curriculum = query.data

  return <section className="mx-auto w-full max-w-5xl flex-1 px-4 py-12 sm:px-6 lg:px-8">
    <Link to="/teacher/courses" className="text-sm font-semibold text-brand-700">← My courses</Link><div className="mt-5"><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-600">Curriculum editor</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-950">{curriculum.title}</h1><p className="mt-3 text-slate-600">Build sections and lessons, then use the arrows to set their order.</p></div>
    {action.isError && <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{action.error.message}</p>}
    <form onSubmit={addSection} className="mt-8 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:flex-row"><label className="min-w-0 flex-1 text-sm font-semibold">New section title<input value={newSectionTitle} onChange={(event) => setNewSectionTitle(event.target.value)} minLength={2} maxLength={160} required className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><button disabled={action.isPending} className="self-stretch rounded-lg bg-brand-600 px-4 py-2 font-semibold text-white disabled:opacity-50 sm:self-end">Add section</button></form>
    {curriculum.sections.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-600">Add a section to begin building your curriculum.</div>}
    <div className="mt-8 space-y-6">{curriculum.sections.map((section, sectionIndex) => <article key={section.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-brand-50 font-bold text-brand-700">{sectionIndex + 1}</span>{editingSection === section.id ? <div className="flex gap-2"><input value={sectionTitle} onChange={(event) => setSectionTitle(event.target.value)} className="rounded-lg border px-3 py-2" autoFocus /><button onClick={() => void saveSection(section.id)} className="font-semibold text-brand-700">Save</button></div> : <h2 className="text-xl font-bold text-slate-950">{section.title}</h2>}</div><div className="flex gap-1"><button type="button" disabled={sectionIndex === 0 || action.isPending} onClick={() => void moveSection(sectionIndex, -1)} aria-label={`Move ${section.title} up`} className="rounded px-2 py-1 disabled:opacity-30">↑</button><button type="button" disabled={sectionIndex === curriculum.sections.length - 1 || action.isPending} onClick={() => void moveSection(sectionIndex, 1)} aria-label={`Move ${section.title} down`} className="rounded px-2 py-1 disabled:opacity-30">↓</button><button type="button" onClick={() => { setEditingSection(section.id); setSectionTitle(section.title) }} className="rounded px-2 py-1 text-sm font-semibold text-slate-600">Edit</button><button type="button" onClick={() => setConfirmation({ title: 'Delete section?', description: `“${section.title}” and all its lessons will be permanently deleted.`, action: (token) => curriculumApi.deleteSection(courseId, section.id, token) })} className="rounded px-2 py-1 text-sm font-semibold text-red-700">Delete</button></div></header>
      <div className="mt-5 space-y-3">{section.lessons.map((lesson, lessonIndex) => <div key={lesson.id} className="rounded-xl border border-slate-200 p-4">{editingLesson?.id === lesson.id ? <LessonForm initial={{ title: lesson.title, description: lesson.description, youtubeVideoId: lesson.youtubeVideoId, isPreview: lesson.isPreview }} busy={action.isPending} onCancel={() => setEditingLesson(null)} onSubmit={async (values) => { await run((token) => curriculumApi.editLesson(courseId, lesson.id, values, token)); setEditingLesson(null) }} /> : <div className="flex flex-col items-start justify-between gap-4 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{lessonIndex + 1}. {lesson.title}</h3>{lesson.isPreview && <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-700">Preview</span>}</div><p className="mt-1 text-sm text-slate-600">{lesson.description}</p><p className="mt-2 break-all font-mono text-xs text-slate-500">YouTube: {lesson.youtubeVideoId}</p></div><div className="flex shrink-0 flex-wrap gap-2"><button disabled={lessonIndex === 0 || action.isPending} onClick={() => void moveLesson(section.id, lessonIndex, -1)} aria-label={`Move ${lesson.title} up`} className="px-1 disabled:opacity-30">↑</button><button disabled={lessonIndex === section.lessons.length - 1 || action.isPending} onClick={() => void moveLesson(section.id, lessonIndex, 1)} aria-label={`Move ${lesson.title} down`} className="px-1 disabled:opacity-30">↓</button><button onClick={() => setEditingLesson(lesson)} className="px-1 text-sm font-semibold text-slate-600">Edit</button><button onClick={() => setConfirmation({ title: 'Delete lesson?', description: `“${lesson.title}” will be permanently deleted.`, action: (token) => curriculumApi.deleteLesson(courseId, lesson.id, token) })} className="px-1 text-sm font-semibold text-red-700">Delete</button></div></div>}</div>)}</div>
      {addingLessonTo === section.id ? <LessonForm busy={action.isPending} onCancel={() => setAddingLessonTo(null)} onSubmit={async (values: LessonFormValues) => { await run((token) => curriculumApi.addLesson(courseId, section.id, values, token)); setAddingLessonTo(null) }} /> : <button type="button" onClick={() => setAddingLessonTo(section.id)} className="mt-4 text-sm font-semibold text-brand-700">+ Add lesson</button>}
    </article>)}</div><ConfirmationDialog open={Boolean(confirmation)} title={confirmation?.title ?? ''} description={confirmation?.description ?? ''} confirmLabel="Delete" busy={action.isPending} onCancel={() => setConfirmation(null)} onConfirm={() => { if (!confirmation) return; void run(confirmation.action).then(() => { showToast('Curriculum updated'); setConfirmation(null) }).catch(() => showToast('Delete failed', 'error')) }} />
  </section>
}
