import { Link } from 'react-router-dom'
import { useAuth } from '../features/auth/context/useAuth'
import { useTeacherDashboard } from '../features/dashboard/hooks/useDashboard'

export function TeacherDashboardPage() {
  const { user } = useAuth()
  const dashboard = useTeacherDashboard()
  return <section className="mx-auto w-full max-w-6xl flex-1 px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-600">Teacher dashboard</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-bold tracking-tight text-slate-950">Welcome, {user?.fullName}</h1><p className="mt-3 text-slate-600">Create, publish, and maintain your learning catalogue.</p></div><Link to="/teacher/courses/new" className="rounded-xl bg-brand-600 px-5 py-3 font-semibold text-white hover:bg-brand-700">Create course</Link></div>
    {dashboard.isPending && <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-slate-200" />)}</div>}
    {dashboard.isError && <div className="mt-10 rounded-2xl border border-red-200 bg-red-50 p-6"><p className="font-semibold text-red-900">Your dashboard could not be loaded.</p><button type="button" onClick={() => dashboard.refetch()} className="mt-3 font-semibold text-red-700">Try again</button></div>}
    {dashboard.data && <><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[{ label: 'Total courses', value: dashboard.data.totalCourses }, { label: 'Published', value: dashboard.data.publishedCourses }, { label: 'Drafts', value: dashboard.data.draftCourses }, { label: 'Enrolled students', value: dashboard.data.totalEnrolledStudents }].map((stat) => <div key={stat.label} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-slate-500">{stat.label}</p><p className="mt-2 text-4xl font-bold text-slate-950">{stat.value}</p></div>)}</div>
      <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-slate-950">Recently updated courses</h2><Link to="/teacher/courses" className="text-sm font-semibold text-brand-700">View all</Link></div>{dashboard.data.recentlyUpdatedCourses.length === 0 ? <p className="mt-5 text-slate-600">Create your first course to see activity here.</p> : <ul className="mt-5 divide-y divide-slate-100">{dashboard.data.recentlyUpdatedCourses.map((course) => <li key={course.id} className="flex items-center justify-between gap-4 py-4"><div><h3 className="font-semibold text-slate-900">{course.title}</h3><p className="mt-1 text-sm text-slate-500">Updated {new Date(course.updatedAt).toLocaleDateString()}</p></div><Link to={`/teacher/courses/${course.id}/edit`} className="text-sm font-semibold text-brand-700">Edit</Link></li>)}</ul>}</div></>}
  </section>
}
