import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { lessonFormSchema, type LessonFormValues } from '../../features/curriculum/schemas/curriculumSchemas'

export function LessonForm({ initial, busy, onCancel, onSubmit }: { initial?: LessonFormValues; busy: boolean; onCancel: () => void; onSubmit: (values: LessonFormValues) => Promise<void> }) {
  const { register, handleSubmit, formState: { errors } } = useForm<LessonFormValues>({ resolver: zodResolver(lessonFormSchema), defaultValues: initial ?? { title: '', description: '', youtubeVideoId: '', isPreview: false } })
  const field = 'mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100'
  return <form onSubmit={handleSubmit(onSubmit)} className="mt-4 space-y-4 rounded-xl border border-brand-100 bg-brand-50/40 p-4"><div><label className="text-sm font-semibold">Lesson title<input {...register('title')} className={field} /></label>{errors.title && <p className="mt-1 text-sm text-red-700">{errors.title.message}</p>}</div><div><label className="text-sm font-semibold">Description<textarea rows={3} {...register('description')} className={field} /></label>{errors.description && <p className="mt-1 text-sm text-red-700">{errors.description.message}</p>}</div><div><label className="text-sm font-semibold">YouTube video ID or URL<input {...register('youtubeVideoId')} className={field} placeholder="dQw4w9WgXcQ" /></label>{errors.youtubeVideoId && <p className="mt-1 text-sm text-red-700">{errors.youtubeVideoId.message}</p>}</div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" {...register('isPreview')} className="size-4" /> Allow public preview</label><div className="flex gap-2"><button disabled={busy} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Save lesson</button><button type="button" onClick={onCancel} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</button></div></form>
}
